### ISSUE TITLE
PKI fails to install using OpenSSL 1.1.0 or higher

### ISSUE THREAD

**Issue by LorneCurrieHomes** [s-u/PKI#18]
We are attempting to install a Shiny-server using R version 3.3.2  When I install the PKI via RSconnect package, I am getting the following error:
```
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (htmltools)
* installing *source* package ‘PKI’ ...
** package ‘PKI’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-hctDwb/r-base-3.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c asn1.c -o asn1.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-hctDwb/r-base-3.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-hctDwb/r-base-3.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c pki-x509.c -o pki-x509.o
pki-x509.c: In function ‘PKI_extract_key’:
pki-x509.c:136:26: error: dereferencing pointer to incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
     if (EVP_PKEY_type(key->type) != EVP_PKEY_RSA)
                          ^~
pki-x509.c: In function ‘get_cipher’:
pki-x509.c:244:40: error: dereferencing pointer to incomplete type ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
  ctx = (EVP_CIPHER_CTX*) malloc(sizeof(*ctx));
                                        ^~~~
pki-x509.c: In function ‘PKI_RSAkeygen’:
pki-x509.c:550:5: warning: ‘RSA_generate_key’ is deprecated [-Wdeprecated-declarations]
     rsa = RSA_generate_key(bits, 65537, 0, 0);
     ^~~
In file included from /usr/include/openssl/rsa.h:13:0,
                 from pki.h:13,
                 from pki-x509.c:1:
/usr/include/openssl/rsa.h:193:1: note: declared here
 DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
 ^
/usr/lib/R/etc/Makeconf:132: recipe for target 'pki-x509.o' failed
make: *** [pki-x509.o] Error 1
ERROR: compilation failed for package ‘PKI’
* removing ‘/usr/local/lib/R/site-library/PKI’
```

The Openssl version is 1.0.2

**Comment by LorneCurrieHomes** [comment]
Found my issue.  It was a conflict with Ubuntu Library's.

**Comment by LorneCurrieHomes** [comment]
I have come accross the same issue.  getting the exact same error.  Is anyone able to help?

TIA

**Comment by s-u** [comment]
The API in OpenSSL 1.1 has changed - it does work with OpenSSL <1.1. I'll see if I can adapt PKI to the new API.

**Comment by s-u** [comment]
Should be now fixed by cc60330

**Comment by LorneCurrieHomes** [comment]
@s-u Thank you.

**Comment by LorneCurrieHomes** [comment]
@s-u When do you think that version 1-4 will be ready for release?
